import { readdirSync, writeFileSync } from 'fs';
import { join, relative } from 'path';
import { fileURLToPath } from 'url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const PHOTOS_DIR = join(__dirname, '..', 'public', 'photos');
const OUTPUT_TS = join(__dirname, '..', 'app', 'getMediaUrl.ts');

const GITHUB_BASE = 'https://raw.githubusercontent.com/Olwynion/postcard-media/main';

function getAllFiles(dir) {
  const files = [];
  const entries = readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...getAllFiles(fullPath));
    } else if (entry.name !== '.DS_Store') {
      files.push(fullPath);
    }
  }
  return files;
}

const files = getAllFiles(PHOTOS_DIR);
const entries = files
  .map((f) => {
    const relPath = relative(PHOTOS_DIR, f);
    const ext = relPath.slice(relPath.lastIndexOf('.')).toLowerCase();

    const encodedPath = relPath.split('/').map(encodeURIComponent).join('/');
    const url = `${GITHUB_BASE}/photos/${encodedPath}`;

    return `  '${relPath}': '${url}'`;
  })
  .join(',\n');

const tsContent = `// Auto-generated by scripts/generate-urls.mjs
// All media: GitHub raw (postcard-media repo)

const mediaUrls: Record<string, string> = {
${entries},
};

export function getMediaUrl(src: string): string {
  const key = src.startsWith('/photos/') ? src.replace('/photos/', '') : src;
  return mediaUrls[key] || src;
}
`;

writeFileSync(OUTPUT_TS, tsContent);
console.log(`Generated ${files.length} entries in ${OUTPUT_TS}`);
console.log(`  Photos: ${files.filter(f => !f.endsWith('.mp4')).length}`);
console.log(`  Videos: ${files.filter(f => f.endsWith('.mp4')).length}`);
