import { put } from '@vercel/blob';
import { readFileSync, readdirSync, statSync, writeFileSync } from 'fs';
import { join, relative } from 'path';
import { fileURLToPath } from 'url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));

const PHOTOS_DIR = join(__dirname, '..', 'public', 'photos');
const OUTPUT_TS = join(__dirname, '..', 'app', 'getMediaUrl.ts');

function getAllFiles(dir) {
  const files = [];
  const entries = readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...getAllFiles(fullPath));
    } else {
      files.push(fullPath);
    }
  }
  return files;
}

function getMimeType(ext) {
  const map = {
    '.jpg': 'image/jpeg',
    '.JPG': 'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.png': 'image/png',
    '.PNG': 'image/png',
    '.gif': 'image/gif',
    '.mp4': 'video/mp4',
    '.webm': 'video/webm',
    '.mov': 'video/quicktime',
    '.MOV': 'video/quicktime',
  };
  return map[ext] || 'application/octet-stream';
}

async function main() {
  if (!process.env.BLOB_READ_WRITE_TOKEN) {
    console.error('Error: BLOB_READ_WRITE_TOKEN environment variable is required');
    console.error('Get it from https://vercel.com/dashboard -> Storage -> Create Blob Store');
    console.error('Then run: BLOB_READ_WRITE_TOKEN=your_token node scripts/upload-blob.mjs');
    process.exit(1);
  }

  console.log('Scanning files in public/photos/...');
  const files = getAllFiles(PHOTOS_DIR);
  console.log(`Found ${files.length} files`);

  const urlMap = {};

  for (const file of files) {
    const relPath = relative(PHOTOS_DIR, file);
    const ext = relPath.slice(relPath.lastIndexOf('.'));
    const content = readFileSync(file);
    const mime = getMimeType(ext);

    console.log(`Uploading: ${relPath} (${(content.length / 1024 / 1024).toFixed(1)}MB)`);

    try {
      const blob = await put(relPath, content, {
        access: 'public',
        contentType: mime,
        addRandomSuffix: false,
      });

      urlMap[relPath] = blob.url;
      console.log(`  -> ${blob.url}`);
    } catch (err) {
      console.error(`  FAILED: ${err.message}`);
    }
  }

  // Generate TypeScript file
  const entries = Object.entries(urlMap)
    .map(([key, url]) => `  '${key}': '${url}'`)
    .join(',\n');

  const tsContent = `// Auto-generated by scripts/upload-blob.mjs
// Maps local media paths to Vercel Blob Storage URLs

const mediaUrls: Record<string, string> = {
${entries},
};

export function getMediaUrl(src: string): string {
  const key = src.startsWith('/photos/') ? src.replace('/photos/', '') : src;
  return mediaUrls[key] || src;
}
`;

  writeFileSync(OUTPUT_TS, tsContent);
  console.log(`\nDone! Generated ${OUTPUT_TS}`);
  console.log(`Total files uploaded: ${Object.keys(urlMap).length}`);
}

main().catch(console.error);
